### ISSUE TITLE
Open Cursor and Open Cursor By Index Assumes ReadOnly Mode of Transactions.

### ISSUE THREAD

**Issue by thousandtyone** [assuncaocharles/ngx-indexed-db#203]
https://github.com/assuncaocharles/ngx-indexed-db/blob/master/projects/ngx-indexed-db/src/lib/ngx-indexed-db.service.ts
Assumes that someone is opening a cursor for reading data:

>  const transaction = createTransaction(db, optionsGenerator(**DBMode.readonly**, storeName, reject, resolve));

Instead of hard coding this the user should be allowed to pick and choose the transaction mode. Should be passed in createCursor and createCursorIndex as parameters. 

Here is my code:

> 
> this.dbService.openCursorByIndex("entries", "clickers", IDBKeyRange.only(this.clicker.id.toString()),(evt) => {
>             var cursor = (<any>evt.target).result;
>             if (cursor) {
>                 cursor.delete();
>                 cursor.continue();
>             }});

And here is the error it produces:

core.js:4127 ERROR DOMException: Failed to execute 'delete' on 'IDBCursor': The record may not be deleted inside a read-only transaction.
    at http://localhost:4200/views-tickers-tickers-module.js:1751:30
    at IDBRequest.__zone_symbol__ON_PROPERTYsuccess (http://localhost:4200/views-tickers-tickers-module.js:1075:21)
    at IDBRequest.wrapFn (http://localhost:4200/polyfills.js:11772:43)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:10923:35)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:70745:33)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:10922:40)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.js:10690:51)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:11005:38)
    at invokeTask (http://localhost:4200/polyfills.js:12173:18)
    at IDBRequest.globalZoneAwareCallback (http://localhost:4200/polyfills.js:12199:21)

I think we need to provide the users an ability to decide in which mode they want to open transactions / cursors?

Happy to provide this Pull Request if you agree with this change.

**Comment by assuncaocharles** [comment]
Hi @thousandtyone 

Sure thing, open the PR :)
