### ISSUE TITLE
Error: Arrow function

### ISSUE THREAD

**Issue by samuellassoie** [assuncaocharles/ngx-indexed-db#208]
Hi,

I have an error when I use old browser because there are arrow function in your code (esm2015) ?
```javascript
function openDatabase(indexedDB, dbName, version, upgradeCallback) {
    return new Promise((resolve, reject) => {
        if (!indexedDB) {
            reject('IndexedDB not available');
        }

```
How can I do to resolve this issue ? Should I create a service and import UMD library ? 

Thans for you anwser

**Comment by assuncaocharles** [comment]
Which browser @samuellassoie ? How can I repro?

**Comment by samuellassoie** [comment]
Chrome 27 which doesn't support arrow function, const, let etc…
I use specifics devices where I can't update the browser

**Comment by samuellassoie** [comment]
When I try to build my app with ngx-indexed-db@6.0.5 , I have this error

```javascript 
Compiling ngx-indexed-db : module as esm5
Warning: Invalid constructor parameter decorator in /Users/slassoie/project/node_modules/ngx-indexed-db/fesm2015/ngx-indexed-db.js:
 () => [
    { type: undefined, decorators: [{ type: Inject, args: [CONFIG_TOKEN,] }] },
    { type: undefined, decorators: [{ type: Inject, args: [PLATFORM_ID,] }] }
]
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected NgxIndexedDBService to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (/Users/slassoie/project/node_modules/@angular/compiler-cli/ngcc/src/host/esm5_host.js:88:23)
    at DelegatingReflectionHost.getInternalNameOfClass (/Users/slassoie/project/node_modules/@angular/compiler-cli/ngcc/src/host/delegating_host.js:89:34)
    at extractInjectableMetadata (/Users/slassoie/project/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:125:69)
    at InjectableDecoratorHandler.analyze (/Users/slassoie/project/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:66:24)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/Users/slassoie/project/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
``` 
for you information, I don't have the problem with the version ngx-indexed-db@5.0.4

Do you have a solution for me ?

Thanks for you answer
