### ISSUE TITLE
ERROR DOMException: Failed to execute 'get' on 'IDBIndex': No key or key range specified.

### ISSUE THREAD

**Issue by tl-mueller** [assuncaocharles/ngx-indexed-db#220]
In some cases, the method getByIndex returns the following error:

```
core.js:9110 ERROR DOMException: Failed to execute 'get' on 'IDBIndex': No key or key range specified.
    at http://localhost:8100/vendor.js:218336:39
    at ZoneDelegate.invoke (http://localhost:8100/polyfills.js:3747:26)
    at Object.onInvoke (http://localhost:8100/vendor.js:71869:33)
    at ZoneDelegate.invoke (http://localhost:8100/polyfills.js:3746:52)
    at Zone.run (http://localhost:8100/polyfills.js:3512:43)
    at http://localhost:8100/polyfills.js:4243:36
    at ZoneDelegate.invokeTask (http://localhost:8100/polyfills.js:3779:31)
    at Object.onInvokeTask (http://localhost:8100/vendor.js:71850:33)
    at ZoneDelegate.invokeTask (http://localhost:8100/polyfills.js:3778:60)
    at Zone.runTask (http://localhost:8100/polyfills.js:3556:47)
```

Does anyone has an idea why this happens?

Within a Promise, I call my method:

```
   const assignedElement = await this.getObjectById(objectReferenceId);
```

The method getObjectById is straightforward:

```
    public async getObjectById(objectId: number, rawData?: boolean): Promise<any> {
        return new Promise((resolve) => {
            this.dbService.getByIndex(store, 'objectId', objectId)
                .subscribe((companyObject) => {
                       resolve(object);
```

I get my query data, but for some reason, the error occurs. Thanks a lot for your help!

**Comment by assuncaocharles** [comment]
Hey, 

Can you repro into a codesandbox?

**Comment by assuncaocharles** [comment]
Closing it since there was no interaction
